---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install git
  ansible.builtin.apt:
    name:
      - git
    state: present
    
- name: Clone repository
  ansible.builtin.git:
    repo: "https://github.com/TeamM0unt41n/node-monitoring.git"
    dest: "/app/"
    recursive: true
    force: true

- name: Startup
  become: true
  community.docker.docker_compose_v2:
    project_src: "/app/server/"
    state: present