services:
  # cadvisor:
  #   restart: unless-stopped
  #   image: gcr.io/cadvisor/cadvisor
  #   volumes:
  #     - /:/rootfs
  #     - /var/run:/var/run
  #     - /sys:/sys
  #     - /var/lib/docker/:/var/lib/docker
  #     - /dev/disk/:/dev/disk
  #   devices:
  #     - /dev/kmsg
  #   command:
  #     - --store_container_labels=true
  #   networks:
  #     - monitoring
    
  node_exporter:
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    networks:
      - monitoring

