[server]
tools-1.ad.m0unt41n.ch ansible_user=root

[client]
tools-2.ad.m0unt41n.ch ansible_user=root
tools-3.ad.m0unt41n.ch ansible_user=root
vulnbox-1.ad.m0unt41n.ch ansible_user=root
vulnbox-2.ad.m0unt41n.ch ansible_user=root
178.105.213.43 ansible_user=root