[server]
10.2.1.106 ansible_user=debian

[client]
10.2.1.101 ansible_user=debian
10.2.1.102 ansible_user=debian
10.2.1.103 ansible_user=debian
10.2.1.104 ansible_user=debian
10.2.1.105 ansible_user=debian