---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "monitoring"
    static_configs:
      - targets:
          - "10.67.1.2:9100"
        labels:
          env: "vuln1"

      - targets:
          - "10.67.2.2:9100"
        labels:
          env: "vuln2"

      - targets:
          - "10.67.3.2:9100"
        labels:
          env: "vuln3"

      - targets:
          - "10.67.1.3:9100"   # Host D
        labels:
          env: "tooling1"

      - targets:
          - "10.67.2.3:9100"   # Host D
        labels:
          env: "tooling2"

      - targets:
          - "node_exporter:9100"   # Host D
        labels:
          env: "gameserver"